### ISSUE TITLE
Gallery submission feedback - Homepage url not a valid page

### ISSUE THREAD

**Issue by yeeha567** [jacobdmontgomery/copyAcrossDataLayers#1]
https://github.com/jacobdmontgomery/copyAcrossDataLayers/blob/c60a0fa0bff5f784b0dea89333132e80be9cafc4/metadata.yaml#L15

**Comment by jacobdmontgomery** [comment]
Hi @yeeha567 this is now fixed in latest version, changed to https://jacob-montgomery.com
