### ISSUE TITLE
Gallery submission feedback - Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by yeeha567** [jacobdmontgomery/copyAcrossDataLayers#2]
When reviewing your template, we've noticed that `gtmOnSuccess` or `gtmOnFailure` are called incorrectly. This is required so that users can sequence their tags correctly.

**Comment by jacobdmontgomery** [comment]
Hi @yeeha567 

I have now added multiple gtmOnFailure calls in possible failure locations, and gtmOnSuccess remains at the end of the code. Is this now ok?
